# Generated by Django 5.0.6 on 2024-09-24 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='info.vacancy'),
        ),
    ]
